" Plugins etc
filetype plugin indent on
syntax on

" Regular backspace
set backspace=indent,eol,start

" Line numbers
set number
set colorcolumn=72

" Go-vim
" Run go imports along with go fmt on each save
let g:go_fmt_command = "goimports"

" Get type info by default when we hover over things
let g:go_auto_type_info = 1

" NerdTree remap to ctrl+g
:nnoremap <C-g> :NERDTreeToggle<CR>

" Useful remaps
" Move esc to home row
inoremap jk <ESC>

" Shortcuts more reachable
let mapleader = "'"

" Highlight all results	
set hlsearch

" Show search results while typing
set incsearch

" Share system keyboard
set clipboard=unnamed

" Spelling
set spell
set spell spelllang=en_us
set spellfile=~/.vim/spellfile.add
highlight clear SpellBad
highlight SpellBad term=reverse ctermfg=9 cterm=undercurl guisp=none
