" Plugins etc
filetype plugin indent on
syntax on

" Regular backspace
set backspace=indent,eol,start

" Line numbers
set number
set colorcolumn=72

" Go-vim
" Run go imports along with go fmt on each save
let g:go_fmt_command = "goimports"

" Get type info by default when we hover over things
let g:go_auto_type_info = 1

" NerdTree remap to ctrl+g
:nnoremap <C-g> :NERDTreeToggle<CR>

